pre-commit: add ruff hook
jupyterhub/grafana-dashboards pull request #104
Opened 2024-04-04 20:00 UTC by consideRatio

2024-04-04 20:15 UTC, yuvipanda requested changes
I'm kinda wary of ruff given it's VC funding, and would prefer we use the same stack we use elsewhere instead (black, etc). Nothing against the people behind ruff specifically! If we want to introduce ruff into the jupyterhub project, I'd like there to be more community consensu before we do so.

2024-04-04 20:16 UTC, consideRatio commented
Ah okay, we can go for the normal stuff - I adopted it after setting it be piloted for use in jupyterhub/jupyterhub

2024-04-04 20:56 UTC, consideRatio commented on dashboards/jupyterhub.jsonnet
> +#!/usr/bin/env -S jsonnet -J ../vendor
I had to use `-S` to not have env parse the content above as a command with spaces in it.

2024-04-04 20:57 UTC, consideRatio commented on dashboards/support.jsonnet
> +#!/usr/bin/env -S jsonnet -J ../vendor
I had to ensure shebangs were added to executable files.

I removed the executable flag for the libsonnet file that renders blank anyhow.

2024-04-05 10:29 UTC, consideRatio commented
@yuvipanda I'll go for a merge now to unblock myself to contribute further, I'll push a merge commit to your PR fixing the conflict caused by this as well

2024-04-05 10:29 UTC, merged