Add --no-tls-verify flag
jupyterhub/grafana-dashboards pull request #74
Opened 2023-04-11 20:43 UTC by itaytalmi

Fixes #73
- Added an optional `--no-tls-verify` flag to `deploy.py` for Grafana instances configured with self-signed certificates.
- Updated `README.md` accordingly.

2023-04-12 06:15 UTC, yuvipanda requested changes

2023-04-12 06:15 UTC, yuvipanda commented on deploy.py
> +        ctx.check_hostname = False
Can you move the conditional check for no_tls_verify here? That way, we pass the context unconditionally to urlopen, and don't have to repeat the `urlopen` in line 35:36

2023-04-12 12:13 UTC, itaytalmi commented
Moving the conditional check wouldn't have helped. However, I just committed an updated version, where the context is always initialized. If `no_tls_verify` is not defined, the context is set to `None`. Otherwise, the context is set to skip TLS verification. Either way, `urlopen` is now only called once.

2023-04-18 13:18 UTC, itaytalmi commented
Hi @yuvipanda, any idea when this can be merged?

2023-04-19 06:29 UTC, merged